### ISSUE TITLE
Build Binaries for Windows

### ISSUE THREAD

**Issue by michaelahlers** [PatternConsulting/opencv#3]
Need 32- and 64-bit binaries for Windows.

**Comment by michaelahlers** [comment]
See comments in issue #9.

**Comment by mscarlett** [comment]
I see that this project hasn't been updated recently, but I can assist with the 32- and 64- bit binaries for Windows since I was able to build these. The ones I built in the <a href="https://github.com/mscarlett/opencv">fork that I created</a> are version 2.4.10, but if you want version 2.4.9 binaries for now then I can also do that.

**Comment by michaelahlers** [comment]
@mscarlett, I saw your work and it looks good! My workload is a bit high at the moment, but I'll soon plan on following up with you when I tackle issue #9.

**Comment by andreldm** [comment]
You don't need to build anything, just download the [installer](https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.9/opencv-2.4.9.exe/download), extract it with 7zip and grab the dll from "opencv\build\java\(x86|x64)\opencv_java249.dll".
I'm really looking forward to use this lib on my project, but the target audience is going to be using Windows :/

**Comment by michaelahlers** [comment]
@vonnieda addressed this in his fork with [issue 1](https://github.com/openpnp/opencv/issues/1). Recommend users migrate to [his package](https://github.com/openpnp/opencv).
